### PR TITLE
DEVOPS-190: replace data bags with chef-vault

### PR DESCRIPTION
**Pull request by toddmichael**
Prefer Chef-Vault model to [encrypted] data bags.

**NOTE**: I've not yet refactored unit tests to reflect this change. I'm wrapping this cookbook and using integration tests there to confirm the functionality of this change. Not the best, but I'm crunched for time.  Will get back to it after I get this deliverable met.

Opened GH-73 to see if there's appetite for this upstream.

### CODE REVIEW

**Comment by toddmichael** [comment]
This is tested and ready for merge.  This chef-vault refactor necessitates two GH-74 submissions: 1 for old upstream version and 1 for this chef-vault version.  Hence, the second commit here.

**Comment by toddmichael** [comment]
Hold off on merging this.  Need to push some conditional logic re the SELinux stuff.

**Comment by netflash** [comment]
is this ready?

**Comment by toddmichael** [comment]
I need to destroy, rebuild and test this today.

**Comment by toddmichael** [comment]
Success. Merging.

**Pull request merged**
